name: "Deploy to staging - v6"

on:
  push:
    branches: [staging]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    environment:
      name: staging
      url: https://staging.example.net
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Echo variable
        shell: bash
        run: echo ${{ secrets.TARGET_BRANCH }} >> target.log
      - name: Save logs
        uses: actions/upload-artifact@v2
        with:
          name: target.log
          path: ./target.log
